<!DOCTYPE html>
<html lang="en"><head>
<script src="LE02_files/libs/clipboard/clipboard.min.js"></script>
<script src="LE02_files/libs/quarto-html/tabby.min.js"></script>
<script src="LE02_files/libs/quarto-html/popper.min.js"></script>
<script src="LE02_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="LE02_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="LE02_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="LE02_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <meta name="author" content="Poshan Niraula">
  <meta name="dcterms.date" content="2026-04-23">
  <title>Coordinates and Reference Systems</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="LE02_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="LE02_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="LE02_files/libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link rel="stylesheet" href="logo.css">
  <link href="LE02_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="LE02_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="LE02_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="LE02_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Coordinates and Reference Systems</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Poshan Niraula 
</div>
</div>
</div>

  <p class="date">2026-04-23</p>
</section>
<section>
<section id="the-shape-of-the-earth" class="title-slide slide level1 center" data-background-color="#1a1a2e" style="color: white;">
<h1>The Shape of the Earth</h1>

</section>
<section id="the-earth-is-not-a-mathematical-shape" class="slide level2">
<h2>The Earth is not a mathematical shape</h2>
<p>The physical surface of the Earth is irregular — mountains, valleys, ocean trenches.</p>
<p>We cannot define coordinates directly on this surface.</p>
<p>We need a <strong>simpler model</strong>.</p>

<img data-src="images/earth-physical-surface.jpg" class="quarto-figure quarto-figure-center r-stretch" width="700"><p><span class="small">Source: https://science.nasa.gov/earth/earth-observatory/blue-marble-next-generation/</span></p>
</section>
<section id="first-approximation-the-geoid" class="slide level2">
<h2>First approximation — the Geoid</h2>
<p>The <strong>geoid</strong> is the shape the ocean would take under gravity alone — no currents, no wind, no temperature differences.</p>
<ul>
<li>An <strong>equipotential surface</strong> of Earth’s gravity field</li>
<li>Irregular — deviates from a smooth shape by ±100 m</li>
<li>Good for defining <strong>heights</strong>, too complex for defining <strong>coordinates</strong></li>
</ul>

<img data-src="images/geoid-earth.png" class="quarto-figure quarto-figure-center r-stretch" width="600"><p><span class="small">Source: https://www.esa.int/ESA_Multimedia/Images/2011/03/New_GOCE_geoid</span></p>
</section>
<section id="second-approximation-the-ellipsoid" class="slide level2">
<h2>Second approximation — the Ellipsoid</h2>
<p>An <strong>ellipsoid</strong> (oblate spheroid) — defined by just two parameters.</p>
<ul>
<li>Semi-major axis <span class="math inline">\(a\)</span> (equatorial radius)</li>
<li>Inverse flattening <span class="math inline">\(1/f\)</span></li>
</ul>
<p>Smooth, mathematically simple, good enough for horizontal coordinates.</p>

<img data-src="images/ellipsoid-cross-section.png" class="quarto-figure quarto-figure-center r-stretch" width="500"><p><span class="small">Source: Wikipedia commons</span></p>
</section>
<section id="three-surfaces-summary" class="slide level2">
<h2>Three surfaces — summary</h2>

<img data-src="images/three-surfaces.png" class="quarto-figure quarto-figure-center r-stretch" width="800"><p><span class="small">Source: https://link.springer.com/article/10.1007/s12517-024-11884-w?fromPaywallRec=true#Fig1</span></p>
<ul>
<li>Physical surface =&gt; Real, irregular</li>
<li>Geoid =&gt; Gravity-based, bumpy; used for Height reference</li>
<li>Ellipsoid =&gt; Mathematical, smooth; Horizontal coordinates</li>
</ul>
</section></section>
<section>
<section id="coordinate-systems" class="title-slide slide level1 center" data-background-color="#1a1a2e" style="color: white;">
<h1>Coordinate Systems</h1>

</section>
<section id="what-is-a-coordinate-system" class="slide level2">
<h2>What is a coordinate system?</h2>
<p>A set of rules for assigning <strong>numbers to points</strong>.</p>
<p>Purely <strong>abstract</strong> — no connection to the Earth yet.</p>
</section>
<section id="attributes-of-a-coordinate-system" class="slide level2">
<h2>Attributes of a coordinate system</h2>
<p>Every coordinate system defines:</p>
<ul>
<li><strong>Number of axes</strong> — 2 or 3</li>
<li><strong>Axis names</strong> — latitude, longitude, easting, X, Y, Z …</li>
<li><strong>Axis directions</strong> — north, east, up …</li>
<li><strong>Axis units</strong> — degrees, metres, feet …</li>
<li><strong>Axis order</strong> — which comes first?</li>
</ul>

<img data-src="images/coordinate-system-axes.png" class="quarto-figure quarto-figure-center r-stretch" width="400"></section>
<section id="many-coordinate-systems-exist" class="slide level2">
<h2>Many coordinate systems exist</h2>
<p>The same point on Earth can be described using different coordinate systems.</p>
<p>We now look at the main types.</p>
</section>
<section id="coordinates-on-a-sphere" class="slide level2">
<h2>Coordinates on a sphere</h2>
<p>On a sphere, position is defined by two angles:</p>
<ul>
<li><strong>Latitude</strong> <span class="math inline">\(\varphi\)</span> — angle from the equatorial plane to a line to the centre</li>
<li><strong>Longitude</strong> <span class="math inline">\(\lambda\)</span> — angle from the prime meridian</li>
</ul>
<p>On a sphere, the surface normal passes through the centre — latitude has only one definition.</p>

<img data-src="images/spherical-coordinates.png" class="quarto-figure quarto-figure-center r-stretch" width="450"><p><span class="small">Source: Wikipedia commons</span></p>
</section>
<section id="coordinates-on-an-ellipsoid" class="slide level2">
<h2>Coordinates on an ellipsoid</h2>
<p>On an ellipsoid, the surface normal <strong>does not</strong> pass through the centre.</p>
<p>This creates two different definitions of latitude:</p>
<ul>
<li><strong>Geodetic latitude</strong> — angle of the surface normal to the equatorial plane</li>
<li><strong>Geocentric latitude</strong> — angle of the line to the centre to the equatorial plane</li>
</ul>
<p>They differ by up to ~11.5 arc-minutes (~21 km) at 45°.</p>

<img data-src="images/geodetic-vs-geocentric-latitude.png" class="quarto-figure quarto-figure-center r-stretch" width="500"><p><span class="small">Source: Wikipedia commons</span></p>
</section>
<section id="ellipsoidal-coordinate-system" class="slide level2">
<h2>Ellipsoidal coordinate system</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Coordinate</th>
<th>Symbol</th>
<th>Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geodetic latitude</td>
<td><span class="math inline">\(\varphi\)</span></td>
<td>−90° to +90°</td>
</tr>
<tr class="even">
<td>Geodetic longitude</td>
<td><span class="math inline">\(\lambda\)</span></td>
<td>−180° to +180°</td>
</tr>
<tr class="odd">
<td>Ellipsoidal height</td>
<td><span class="math inline">\(h\)</span></td>
<td>metres above ellipsoid</td>
</tr>
</tbody>
</table>
<ul>
<li>2D version: <span class="math inline">\((\varphi, \lambda)\)</span></li>
<li>3D version: <span class="math inline">\((\varphi, \lambda, h)\)</span></li>
</ul>

<img data-src="images/geodetic-latitude-longitude.png" class="quarto-figure quarto-figure-center r-stretch" width="450"><p><span class="small">Source: Wikipedia commons</span></p>
</section>
<section id="geocentric-cartesian-system" class="slide level2">
<h2>Geocentric Cartesian system</h2>
<p>Origin at Earth’s <strong>centre of mass</strong>. Three straight-line axes.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Axis</th>
<th>Points toward</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>X</td>
<td>Equator ∩ Prime Meridian</td>
</tr>
<tr class="even">
<td>Y</td>
<td>Equator ∩ 90°E</td>
</tr>
<tr class="odd">
<td>Z</td>
<td>North Pole</td>
</tr>
</tbody>
</table>
<p>Units: metres. No ellipsoid needed.</p>
<p>Used in GNSS processing and satellite geodesy.</p>

<img data-src="images/geocentric-cartesian.png" class="quarto-figure quarto-figure-center r-stretch" width="450"><p><span class="small">Source: Wikipedia commons</span></p>
</section>
<section id="conversion-between-ellipsoidal-and-geocentric" class="slide level2">
<h2>Conversion between ellipsoidal and geocentric</h2>
<p>These describe the <strong>same point</strong> — conversion is <strong>exact</strong>.</p>
<p><strong>Ellipsoidal → Geocentric:</strong> Section 2.2.4 has conversion formulas</p>
</section>
<section id="projected-coordinate-systems" class="slide level2">
<h2>Projected coordinate systems</h2>
<p>Convert curved <span class="math inline">\((\varphi, \lambda)\)</span> to flat <span class="math inline">\((E, N)\)</span> — Easting and Northing.</p>
<ul>
<li>Units: metres</li>
<li>Enables flat maps, distance/area calculations on a plane</li>
<li>Always introduces <strong>distortion</strong> (shape, area, distance, or direction)</li>
</ul>
<p>We cover projections in detail in Lectures 4 and 5.</p>

<img data-src="images/projection-types-preview.png" class="quarto-figure quarto-figure-center r-stretch" width="600"><p><span class="small">Source: Wikimedia commons</span></p>
</section>
<section id="local-engineering-coordinate-systems" class="slide level2">
<h2>Local engineering coordinate systems</h2>
<p>For small areas — construction sites, buildings, bridges.</p>
<ul>
<li>Origin at a convenient local point</li>
<li>Axes: typically East, North, Up</li>
<li>Earth’s curvature ignored (area small enough)</li>
<li>Units: metres</li>
</ul>
<p>Must be connected to a global CRS to integrate with other data.</p>
<!-- ![](images/local-engineering-coords.png){fig-align="center" width="500"} -->
</section>
<section id="gravity-related-height-systems" class="slide level2">
<h2>Gravity-Related Height Systems</h2>
<p>GPS gives <strong>ellipsoidal height</strong> <span class="math inline">\(h\)</span> — height above the ellipsoid.</p>
<p>We usually want <strong>orthometric height</strong> <span class="math inline">\(H\)</span> — height above the geoid (“sea level”).</p>
<p><span class="math display">\[h = H + N\]</span></p>
<p>where <span class="math inline">\(N\)</span> is the <strong>geoid undulation</strong> (geoid height above/below the ellipsoid).</p>

<img data-src="images/earth-surfaces-comparison.png" class="quarto-figure quarto-figure-center r-stretch" width="600"></section>
<section class="slide level2">

</section></section>
<section>
<section id="datums" class="title-slide slide level1 center" data-background-color="#1a1a2e" style="color: white;">
<h1>Datums</h1>

</section>
<section id="what-is-a-datum" class="slide level2">
<h2>What is a datum?</h2>
<p>A coordinate system is abstract — floating in mathematical space.</p>
<p>A <strong>datum</strong> anchors it to the <strong>real Earth</strong>.</p>
<p>It defines:</p>
<ul>
<li><strong>Where</strong> the origin is</li>
<li><strong>How</strong> the axes are oriented</li>
<li><strong>What scale</strong> is used</li>
</ul>
</section>
<section id="without-a-datum" class="slide level2">
<h2>Without a datum</h2>
<p>Same coordinate system, no anchor → coordinates are meaningless.</p>
<p>With a datum → every number refers to a specific place on Earth.</p>

<img data-src="images/datum-concept.png" class="quarto-figure quarto-figure-center r-stretch" width="600"><p><span class="small">Source: Iliffe, Jonathan , and Roger Lott . 2008. Datums and Map Projections for Remote Sensing, GIS, and Surveying. Whittles Pub. CRC Press, Scotland, UK.</span></p>
</section>
<section id="geodetic-datum" class="slide level2">
<h2>Geodetic datum</h2>
<p>A <strong>geodetic datum</strong> specifically anchors an ellipsoid to the Earth for defining latitude and longitude.</p>
<p>Two ingredients:</p>
<ol type="1">
<li><strong>Which ellipsoid</strong> (shape and size)</li>
<li><strong>How it is positioned and oriented</strong> relative to the Earth</li>
</ol>
</section>
<section id="before-satellites-local-datums" class="slide level2">
<h2>Before satellites — local datums</h2>
<p>Steps to realise a local datum:</p>
<ol type="1">
<li><strong>Choose an ellipsoid</strong> that fits your region well (e.g., Bessel 1841)</li>
<li><strong>Pick a fundamental point</strong> on the surface (e.g., Rauenberg, Germany)</li>
<li><strong>Align the ellipsoid</strong> so its normal matches gravity direction at that point</li>
<li><strong>Orient</strong> the minor axis parallel to Earth’s rotation axis</li>
<li><strong>Survey outward</strong> from the fundamental point to build a network</li>
</ol>
</section>
<section id="local-datums-the-result" class="slide level2">
<h2>Local datums — the result</h2>
<ul>
<li>Fits well <strong>near the fundamental point</strong></li>
<li>Gets worse <strong>further away</strong></li>
<li>Every country built their own → many datums worldwide</li>
</ul>

<img data-src="images/local-vs-geocentric-ellipsoid.png" class="quarto-figure quarto-figure-center r-stretch" width="700"><p><span class="small">Source: Kalu, I., Ndehedehe, C. E., Okwuashi, O., &amp; Eyoh, A. E. (2022). A comparison of existing transformation models to improve coordinate conversion between geodetic reference frames in Nigeria. Modeling Earth Systems and Environment, 8(1), 611-624.</span></p>
</section>
<section id="after-satellites-geocentric-datums" class="slide level2">
<h2>After satellites — geocentric datums</h2>
<p>Satellites see the <strong>whole Earth</strong> → we can locate the centre of mass.</p>
<p>Steps to realise a geocentric datum:</p>
<ol type="1">
<li>Define the origin (centre of mass), axis directions, and scale</li>
<li>Observe from a global network using VLBI, SLR, GNSS, DORIS</li>
<li>Compute station coordinates as (X, Y, Z) in a consistent global frame</li>
<li>Assign velocities to account for plate tectonics</li>
<li>Optionally associate an ellipsoid (e.g., GRS 80) when users want lat/lon</li>
</ol>
<p>Result: consistent worldwide, no regional bias.</p>
</section>
<section id="many-ellipsoids-many-datums" class="slide level2">
<h2>Many ellipsoids, many datums</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Datum</th>
<th>Ellipsoid</th>
<th>Type</th>
<th>Region</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DHDN</td>
<td>Bessel 1841</td>
<td>Local</td>
<td>Germany</td>
</tr>
<tr class="even">
<td>ED50</td>
<td>International 1924</td>
<td>Local</td>
<td>Europe</td>
</tr>
<tr class="odd">
<td>NAD27</td>
<td>Clarke 1866</td>
<td>Local</td>
<td>North America</td>
</tr>
<tr class="even">
<td>NAD83</td>
<td>GRS 80</td>
<td>Geocentric</td>
<td>North America</td>
</tr>
<tr class="odd">
<td>ETRS89</td>
<td>GRS 80</td>
<td>Geocentric</td>
<td>Europe</td>
</tr>
<tr class="even">
<td>WGS 84</td>
<td>WGS 84</td>
<td>Geocentric</td>
<td>Global</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="coordinate-reference-systems" class="title-slide slide level1 center" data-background-color="#1a1a2e" style="color: white;">
<h1>Coordinate Reference Systems</h1>

</section>
<section id="crs-coordinate-system-datum" class="slide level2">
<h2>CRS = Coordinate System + Datum</h2>
<p><span class="math display">\[\boxed{\text{CRS} = \text{Coordinate System} + \text{Datum}}\]</span></p>
<p>The coordinate system defines <strong>how numbers work</strong>.</p>
<p>The datum defines <strong>where they point</strong>.</p>
<p>Together: unambiguous positions on Earth.</p>
</section>
<section id="same-coordinate-system-different-datums" class="slide level2">
<h2>Same coordinate system, different datums</h2>
<p>All use ellipsoidal coordinates (latitude °, longitude °) — but different anchors.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>CRS</th>
<th>Datum</th>
<th>EPSG</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>WGS 84 geographic</td>
<td>WGS 84</td>
<td>4326</td>
</tr>
<tr class="even">
<td>ETRS89 geographic</td>
<td>ETRS89</td>
<td>4258</td>
</tr>
<tr class="odd">
<td>ED50 geographic</td>
<td>ED50</td>
<td>4230</td>
</tr>
</tbody>
</table>
<p>Münster in each:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>CRS</th>
<th>Latitude</th>
<th>Longitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>WGS 84</td>
<td>51.96885°</td>
<td>7.66508°</td>
</tr>
<tr class="even">
<td>ED50</td>
<td>51.96961°</td>
<td>7.666295°</td>
</tr>
</tbody>
</table>
<p>Same point. Different numbers. Different datum.</p>
</section>
<section id="same-datum-different-coordinate-systems" class="slide level2">
<h2>Same datum, different coordinate systems</h2>
<p>All anchored to WGS 84 — but numbers assigned differently.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>CRS</th>
<th>Coord. System</th>
<th>EPSG</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>WGS 84 geographic</td>
<td>lat/lon (°)</td>
<td>4326</td>
</tr>
<tr class="even">
<td>WGS 84 geocentric</td>
<td>X, Y, Z (m)</td>
<td>4978</td>
</tr>
<tr class="odd">
<td>WGS 84 / UTM 32N</td>
<td>E, N (m)</td>
<td>32632</td>
</tr>
</tbody>
</table>
<p>Same point, same datum, different numbers.</p>
</section></section>
<section>
<section id="itrs-and-realisations" class="title-slide slide level1 center" data-background-color="#1a1a2e" style="color: white;">
<h1>ITRS and Realisations</h1>

</section>
<section id="itrs-the-definition" class="slide level2">
<h2>ITRS — the definition</h2>
<p><strong>International Terrestrial Reference System</strong></p>
<ul>
<li>Origin: Earth’s centre of mass</li>
<li>Z axis: IERS Reference Pole</li>
<li>X axis: IERS Reference Meridian ∩ Equator</li>
<li>Unit: SI metre</li>
<li>Maintained by: IERS</li>
</ul>
<p>This is a <strong>theoretical definition</strong> — a set of conventions on paper.</p>
</section>
<section id="itrf-the-realisation" class="slide level2">
<h2>ITRF — the realisation</h2>
<p><strong>International Terrestrial Reference Frame</strong></p>
<p>The physical realisation: actual coordinates and velocities of real stations.</p>
<p>Built from four observation techniques: VLBI, SLR, GNSS, DORIS</p>

<img data-src="images/itrf-stations.png" class="quarto-figure quarto-figure-center r-stretch" width="600"><p>[Source: https://itrf.ign.fr/en/network/map] {.small}</p>
</section>
<section id="itrf-realisations-over-time" class="slide level2">
<h2>ITRF realisations over time</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Realisation</th>
<th>Reference epoch</th>
<th>Released</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ITRF2000</td>
<td>1997.0</td>
<td>2001</td>
</tr>
<tr class="even">
<td>ITRF2005</td>
<td>2000.0</td>
<td>2007</td>
</tr>
<tr class="odd">
<td>ITRF2008</td>
<td>2005.0</td>
<td>2010</td>
</tr>
<tr class="even">
<td>ITRF2014</td>
<td>2010.0</td>
<td>2016</td>
</tr>
<tr class="odd">
<td><strong>ITRF2020</strong></td>
<td><strong>2015.0</strong></td>
<td><strong>2022</strong></td>
</tr>
</tbody>
</table>
<p>Each includes <strong>station velocities</strong> — because plates move.</p>
<p>Coordinates are only valid at the reference epoch.</p>
</section>
<section id="etrs89-europes-solution" class="slide level2">
<h2>ETRS89 — Europe’s solution</h2>
<p>Problem: in ITRF, European stations drift ~2.5 cm/year northeast.</p>
<p>Solution: <strong>ETRS89</strong> — a reference frame that <strong>moves with the Eurasian plate</strong>.</p>
<ul>
<li>Coordinates of European stations stay (nearly) constant over time</li>
<li>Coincided with ITRF at epoch 1989.0</li>
<li>Used by all European national mapping agencies</li>
</ul>
<!-- ![](images/etrs89-concept.png){fig-align="center" width="600"} -->
</section></section>
<section>
<section id="wgs-84" class="title-slide slide level1 center" data-background-color="#1a1a2e" style="color: white;">
<h1>WGS 84</h1>

</section>
<section id="wgs-84-1" class="slide level2">
<h2>WGS 84</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Property</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ellipsoid</td>
<td><span class="math inline">\(a\)</span> = 6,378,137 m, <span class="math inline">\(1/f\)</span> = 298.257223563</td>
</tr>
<tr class="even">
<td>Origin</td>
<td>Earth’s centre of mass</td>
</tr>
<tr class="odd">
<td>Maintained by</td>
<td>US NGA (National Geospatial-Intelligence Agency)</td>
</tr>
<tr class="even">
<td>Realised through</td>
<td>GPS satellite orbits + ~17 tracking stations</td>
</tr>
</tbody>
</table>
</section>
<section id="wgs-84-realisations" class="slide level2">
<h2>WGS 84 Realisations</h2>
<ul>
<li><strong>Original (1987)</strong> — based on Doppler observations, ~1–2 m accuracy</li>
<li><strong>G730 (Jan 1994)</strong> — aligned to ITRF91</li>
<li><strong>G873 (Jan 1997)</strong> — aligned to ITRF94</li>
<li><strong>G1150 (Jan 2002)</strong> — aligned to ITRF2000</li>
<li><strong>G1674 (Feb 2012)</strong> — aligned to ITRF2008</li>
<li><strong>G1762 (Oct 2013)</strong> — aligned to ITRF2008</li>
<li><strong>G2139 (Jan 2021)</strong> — aligned to ITRF2014</li>
</ul>
<p>The “G” number is the <strong>GPS week number</strong> when the realisation became operational.</p>
</section>
<section id="wgs-84-how-it-is-tied-to-itrf" class="slide level2">
<h2>WGS 84 — how it is tied to ITRF</h2>
<p>WGS 84 is periodically <strong>re-aligned</strong> to the latest ITRF:</p>
<ol type="1">
<li>NGA computes coordinates of its tracking stations <strong>in ITRF</strong></li>
<li>These become the new <strong>WGS 84 station coordinates</strong></li>
<li>GPS orbits are computed relative to these stations</li>
<li>Your receiver’s position is effectively in that realisation</li>
</ol>
</section></section>
<section>
<section id="why-latitude-and-longitude-are-not-unique" class="title-slide slide level1 center" data-background-color="#1a1a2e" style="color: white;">
<h1>Why Latitude and Longitude Are Not Unique</h1>

</section>
<section id="the-same-latlon-can-mean-different-places" class="slide level2">
<h2>The same lat/lon can mean different places</h2>
<p>The values <span class="math inline">\(\varphi = 51.969°\)</span>, <span class="math inline">\(\lambda = 7.665°\)</span> are just numbers.</p>
<p>Their meaning depends on:</p>
<ul>
<li><strong>Which ellipsoid?</strong> (Bessel, GRS 80, WGS 84 …)</li>
<li><strong>Which datum?</strong> (DHDN, ED50, ETRS89, WGS 84 …)</li>
<li><strong>Which realisation?</strong> (WGS 84 G730 vs.&nbsp;G2139 …)</li>
<li><strong>Which epoch?</strong> (2010.0 vs.&nbsp;2025.0 in ITRF …)</li>
</ul>
</section>
<section id="how-much-can-it-shift" class="slide level2">
<h2>How much can it shift?</h2>
<p>The same physical point — different lat/lon depending on the datum:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>From → To</th>
<th>shift</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ED50 → WGS 84 (Münster)</td>
<td>118.9 m</td>
</tr>
<tr class="even">
<td>NAD27 → NAD83 (New York)</td>
<td>36.4 m</td>
</tr>
<tr class="odd">
<td>DHDN → ETRS89 (Münster)</td>
<td>163 m</td>
</tr>
<tr class="even">
<td>ITRF2014 epoch 2010 → epoch 2025</td>
<td>40 cm (2.5 cm per year)</td>
</tr>
<tr class="odd">
<td>WGS 84 (1990) → WGS 84 (2024)</td>
<td>~1–2 m (documented)</td>
</tr>
</tbody>
</table>
<p>Without knowing the datum, coordinates are <strong>ambiguous</strong>.</p>
</section>
<section id="summary" class="slide level2">
<h2>Summary</h2>
<ol type="1">
<li><p>The Earth is not mathematical → we approximate with <strong>geoid</strong> and <strong>ellipsoid</strong></p></li>
<li><p>A <strong>coordinate system</strong> defines axes, units, directions — but is abstract</p></li>
<li><p>A <strong>datum</strong> anchors the coordinate system to the real Earth</p></li>
<li><p><strong>CRS = Coordinate System + Datum</strong> — the complete package</p></li>
<li><p>Local datums (pre-satellite) → geocentric datums (post-satellite)</p></li>
<li><p><strong>ITRF</strong> is the most accurate global frame; <strong>ETRS89</strong> is Europe’s plate-fixed version</p></li>
<li><p><strong>WGS 84</strong> is periodically aligned to ITRF but has multiple realisations</p></li>
<li><p>Latitude and longitude are <strong>not unique</strong> without specifying the CRS</p></li>
</ol>
</section>
<section id="some-videos-explaining-the-concepts" class="slide level2">
<h2>Some videos explaining the concepts</h2>
<p>https://www.youtube.com/watch?v=kXTHaMY3cVk</p>
<p>https://www.youtube.com/watch?v=ZFe_rZccGOQ</p>
</section>
<section id="for-lecture-3" class="slide level2">
<h2>For Lecture 3</h2>
<p>Read Chapter 3 of “datums and map projection” (1st edition) and sections 2.3.4 to 2.5.2 of the coursebook</p>
<p>Think about:</p>
<ul>
<li>Are vertical datums related to horizontal datums? If yes, in which way?</li>
<li>List two different types of height, and name their differences.</li>
<li>What is the difference between the normal and the vertical?</li>
<li>Why could the adoption of a single vertical datum over large distances be problematic for height measurement?</li>
</ul>
<p>Submit questions to Learnweb by Wednesday noon.</p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="LE02_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="LE02_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="LE02_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="LE02_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="LE02_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="LE02_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="LE02_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="LE02_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="LE02_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="LE02_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>